name: Package Application with Pyinstaller
on: [push, pull_request]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [macos-latest]
        python-version: ['3.7']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install pip
        run: python -m pip install py2app
      - name: upgrade pip
        run: python -m pip install --upgrade pip
    - name: downgrade setuptools
        run: python -m pip install --upgrade 'setuptools<45.0.0'
      - name: install requirements.txt
        run: python -m pip install -r requirements.txt
      - name: Build app
        run: python3 setup.py py2app
      - uses: actions/upload-artifact@v2
        with:
          name: backupfriend-client-macos
          path: src/dist/
