name: Package Application with Pyinstaller
on: [push, pull_request]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [macos-latest]
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install pip
        run: python -m pip install py2app
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: downgrade setuptools
        run: python -m pip install --upgrade 'setuptools<45.0.0'
      - name: install requirements.txt
        run: python -m pip install -r requirements.txt
      - name: Build app
        run: python3 setup.py py2app
      - name: Codesign executable
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        run: |
          echo ${MACOS_CERTIFICATE} | base64 --decode > certificate.p12
          security create-keychain -p build.keychain build.keychain1 security default-keychain -s build.keychain
          security unlock-keychain -p build.keychain build.keychain1
          security import certificate.p12 -k build.keychain1 -P ${MACOS_CERTIFICATE_PWD} -T /usr/bin/codesign
          security find-identity -v
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k build.keychain1 build.keychain
          /usr/bin/codesign --force -s <identity-id> dist/Subreddit.app -v
      - uses: actions/upload-artifact@v2
        with:
          name: backupfriend-client-macos
          path: dist/
